# Generated by Django 5.0.6 on 2024-07-04 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
    ]
